olist_redshift:
  target: dev
  outputs:
    dev:
      type: redshift
      host: phucvu-de-wg-dev.701201543509.ap-southeast-1.redshift-serverless.amazonaws.com
      user: phucvuadmin
      password: rs!mHN|lkq7Vk^~BM>P0V5Gq~+0pzQT-es*GPvxzuKmY<gT?Z_53
      port: 5439
      dbname: dev
      schema: olist_sales
      threads: 1
      connect_timeout: 60
      sslmode: require